<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Quote;
use App\Models\Subcategory;
use App\Models\User;
use Illuminate\Http\Request;

class QuoteController extends Controller
{
    public function index()
    {
        $quotes = Quote::with(['subcategory', 'user'])->latest()->paginate(20);
        return view('admin.quotes.index', compact('quotes'));
    }

    public function show(Quote $quote)
    {
        $quote->load('subcategory', 'user');
        return view('admin.quotes.show', compact('quote'));
    }

    public function destroy(Quote $quote)
    {
        $quote->delete();
        return redirect()->route('admin.quotes.index')
                         ->with('success', 'Quote deleted.');
    }

    /* 
     * Quotes are normally generated by the public form,
     * so we typically don't need create/store/edit/update here.
     * If you want admin‑side editing, you can add those methods similarly.
     */
}
